# Generated by Django 5.0.1 on 2024-08-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_seasonalevents_seasonalevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_digtial',
            new_name='is_digital',
        ),
    ]
